#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from dotenv import load_dotenv
from sqlalchemy.engine import make_url

from pkg.database.connector import (
    create_database_if_missing,
    load_schema,
    normalize_mysql_scheme,
    verify_sqlalchemy_connection,
)

DEFAULT_ENV_FILE = Path(".env")


def parse_database_url(database_url: str) -> dict[str, str | int]:
    normalized_url = normalize_mysql_scheme(database_url)
    url = make_url(normalized_url)
    scheme = url.drivername or ""
    if scheme in ("mysql", "mysqlconnector", "mysqldb"):
        url = url.set(drivername="mysql+pymysql")
        scheme = "mysql+pymysql"

    if scheme != "mysql+pymysql":
        raise ValueError(
            "Unsupported database URL. Use a MySQL URL with mysql:// or mysql+pymysql://"
        )

    database = url.database
    if not database:
        raise ValueError("The database name must be provided in the connection URL.")

    return {
        "driver": scheme,
        "host": url.host or "127.0.0.1",
        "port": url.port or 3306,
        "database": database,
        "user": url.username or "",
        "password": url.password or "",
        "database_url": str(url),
    }


def format_env_values(settings: dict[str, str | int]) -> str:
    lines = [
        "# Generated by sync_to_railway.py",
        "# Copy this file to .env locally, and keep secrets out of source control.",
        "",
        "DATABASE_DRIVER=mysql+pymysql",
        f"DATABASE_URL={settings['database_url']}",
        f"MYSQL_HOST={settings['host']}",
        f"MYSQL_PORT={settings['port']}",
        f"MYSQL_DATABASE={settings['database']}",
        f"MYSQL_USER={settings['user']}",
        f"MYSQL_PASSWORD={settings['password']}",
        "",
        "# Application settings",
        "SECRET_KEY=change-this-secret",
    ]
    return "\n".join(lines) + "\n"


def write_env_file(env_path: Path, contents: str) -> None:
    env_path.write_text(contents, encoding="utf-8")
    print(f"Wrote env file to: {env_path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Synchronize Railway MySQL connection details into a local .env file."
    )
    parser.add_argument(
        "database_url",
        help="Railway MySQL connection string, e.g. mysql://user:pass@host:port/db",
    )
    parser.add_argument(
        "--env-file",
        default=str(DEFAULT_ENV_FILE),
        help="Path to write environment variables to (default: .env)",
    )
    parser.add_argument(
        "--provision",
        action="store_true",
        help="Create the database if missing and load the baseline schema after writing .env.",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Verify SQLAlchemy can connect to the configured database after writing .env.",
    )
    args = parser.parse_args()

    env_path = Path(args.env_file)
    settings = parse_database_url(args.database_url)
    write_env_file(env_path, format_env_values(settings))

    load_dotenv(dotenv_path=env_path, override=True)

    if args.provision:
        print("Provisioning database and loading schema...")
        create_database_if_missing()
        load_schema()
        print("Provisioning complete.")

    if args.verify:
        print("Verifying database connection...")
        verification = verify_sqlalchemy_connection()
        print("Connection verified:")
        for key, value in verification.items():
            print(f"  {key}: {value}")


if __name__ == "__main__":
    main()
